sudo: required
dist: trusty
os:
- linux
- osx
language: cpp

before_install: ". scripts/ci/$TRAVIS_OS_NAME/before_install.sh"
install: ". scripts/ci/$TRAVIS_OS_NAME/install.sh"
script: ". scripts/ci/$TRAVIS_OS_NAME/script.sh"
after_success: ". scripts/ci/$TRAVIS_OS_NAME/after_success.sh"
env:
  global:
    secure: csOpCKoSd+khEKl3CG9+2MkK+9dMA2gu0HTDJ0cZ4hCYVyTs1i88uO/Pf9vcPqc5r2AbHpC+pmQH36Qkvb6JBJcWK9m3HTqdbBTrg2nKaaWniWXUZwD3bo4e/zX08mg7DG/HdGgplc/wkGn6gsois8somaVZmexA/LFY1OIKQUfVvs5SScpnYcDL/MzIuVv+jdgeaGCnubtFY0y5ZrlgRweHt4rCwV0Wxlozes7wn1fFwa5tHhAzbIBsj1pol/wqg6wGdhGguRY4GHgU1BK102ASGXxsG6XZuCIyhdWcAln+fcmrtovF1nWcpfucd49yp7Qvfev5sDK9Q4y1BUu3wC+FVps59m6o738vPNOTK6rLVSZ2zu+DLYcYjD1PZjoAwmvGxEWgKvhh1ZR3/Buq9ftEZE2pEKE9W/HJVXb0UZqDCez/ptEeERd0sE79c4OvOhep4iwbjFo9gnrceKczBI2XBODybk3BJkYipm62mi223ygr7iROchKEsaLREDOMiMj7SkqSzvqRkDUrqKLRFTQv4xVSzwttTQM43XWgNrfjJhivEAg7PsgKpEPHwbkNFTIMTOwnBYKq487AVUkLJpDnczJLq8brnS0DPZ0SrjQqJWxjc/FT+N9jPVXuxDLEkoTFSn5fqzxS32a7QMpa4kg3mYxRSgPwLXw/tHpsXfY=

#only watch master and tagged release
branches:
  only:
    - /^v.*$/
    - master

